name: Run Python Test Daily
on:
  workflow_dispatch:
  schedule:
    - cron:  "* 0/12 * * *"  #'*/60 * * * *'
env:
  GITHUB_USER_NAME: syjsu
  GITHUB_USER_EMAIL: syjsu@qq.com
jobs:
  my_job:
    name: test-python
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          python hello.py
