name: Run Python
on:
  workflow_dispatch:
  push:
  schedule:
    - cron:  "* 9/9 * * *"
jobs:
  my_job:
    name: run-python
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      
      - name: 1. Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: 2. Run Python Script
        run: |
          python test.py
          
      - name: 3. commit and push 
        run: |
          git diff
          git config --global user.email "syjsu@qq.com" && git config --global user.name "syjsu"
          git pull
          git add -A
          git commit -m "Update files" || exit 0
          git push
