name: Run-Swift
on:
  workflow_dispatch:
  push:
jobs:
  my_job:
    runs-on: macos-latest
    steps:
      - name: Running playground
      - uses: actions/checkout@v2
      - uses: syjsu/history@master
